name: softwars_test_task
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  scaffold_gradient_background: ^1.0.3+1
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  equatable: ^2.0.5
  http: ^0.13.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
